#!/bin/bash

# author: @n132 ;)
# Check if the first parameter is "debug"
if [ "$1" == "debug" ]; then
    # Run gdb with the specified options
    NL DEBUG
    gdb ./vmlinux -x ./dbg
else
    echo "Not in debug mode."
fi
