#!/usr/bin/python3

peda = """
source ~/peda/peda.py
source ~/Pwngdb/pwngdb.py
source ~/Pwngdb/angelheap/gdbinit.py

define hook-run
python
import angelheap
angelheap.init_angelheap()
end
end
"""
pwndbg = """
source ~/pwndbg/gdbinit.py
source ~/Documents/github/gdb-pt-dump/pt.py
"""

import sys

switch = sys.argv[1]
if switch == "peda":
    content = peda
elif switch == "pwndbg":
    content = pwndbg
else:
    print(f"[-] Invalid plugin: {switch}")
    exit(1)
print(f"[+] Deploying {switch}...")
from pathlib import Path
with open(Path.home()/".gdbinit",'w') as f:
    f.write(content)
print(f"[+] Deployed {switch}.")
